### ISSUE TITLE
Evaluation Metric

### ISSUE THREAD

**Issue by GostInShell** [scenenn/shrec17#3]
hi！
I notice that in the paper [SHREC’17: RGB-D to CAD Retrieval with ObjectNN Dataset](https://www.cs.umb.edu/~craigyu/papers/shrec17.pdf) the `precision` and `recall` are mostly the same in **Table. 3**. And I check the evaluation code. The only difference is that `precison` is divided by the length of the query list and `recall` is divided by the number of the ground-truth class members. So since these two are equal, does it mean that **the query list length is defaultly set to be equal to the the number of the ground-truth class members**. If this is correct then under what circumstances, can these two metrics be different as some of results show in**Table. 3** ?

**Comment by pqhieu** [comment]
Hi,

Thanks for your interest. The issue with precision and recall being the same is because most of the methods return ALL of the objects in the predicted category as their answers. In this case the number of retrieved objects (used in precision) and the number of relevant objects (used in recall) will be the same.

Hope this helps.
